### ISSUE TITLE
A few corrections / enhancements

### ISSUE THREAD

**Issue by ThomasFreedman** [BitSharesEurope/bitshares-whitepapers#3]
You use the word "Identical" describing the codebase used for the testnet relative to the public BitShares network. This was in your opening paragraph on the left, and on the right in section 2.1 you say "almost identical" codebases. Consider adding an example of such a "minor" change, like  the core token name change from BTS to TEST. It might also not hurt to describe WHY that name change is required. Is it to prevent testnet tokens from being used on the public BitShares network? Is it only for human referal / convenience? Doesn't the chainID prevent interchange between the testnnet and BitShares blockchain? 

You incorrectly use the word "subsequently" instead of the word "sequentially" in describing the distinctions between blocks, transactions and operations in section 3 under the paragraph "Transactions and Operations", 2nd paragraph (executed subsequently just means to execute after. Execute sequentially is an explicit example of ordering of items).

Paragrapgh 5.2 describing how one participant used his block validating node to produce blocks - this needs to be elaborated on in more detail. Was this a specially compiled version? How does a witness validate (blocks / transactions?) without being a block producer? Your wording makes it sound like one specific participant was doing something unusual, and that isn't described very well IMO. That paragraph also ends with a period, and the next page with a heading of "5.3 BLOCK CONFIRMATION TIMES" begins with "that can process the same amount..." appears to be the last part of a sentence started elsewhere.

Lastly I wished the paper was a bit more explicit in identifying where the bottlenecks remain, however it presents all of the info in a coherent, positive light and provides direction for subsequent testing, investigation and benchmarking to be conducted. 

You have done a marvelous job in putting this paper together xeroc, bravo!

**Comment by xeroc** [comment]
Thanks a bunch!
